# docker-compose.yml
version: "3.8"

services:
  spotify-mcp:
    build:
      context: .
    container_name: dj_mcp_server_for_spotify
    ports:
      - "8000:8000"
    volumes:
      # tokens ディレクトリ全体をマウント（tokensフォルダが空でも問題ない）
      - ./tokens:/app/tokens
    env_file:
      - .env
    restart: unless-stopped
